// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBozUY40lu7R0AtvushLZc6yTn1L0w52nM',
    appId: '1:578610636419:web:dd4452bf43d1f2e2a35db6',
    messagingSenderId: '578610636419',
    projectId: 'direkapp-a48a8',
    authDomain: 'direkapp-a48a8.firebaseapp.com',
    storageBucket: 'direkapp-a48a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmNPkK5e96EYLTkrxZ_gGDYtVsdRB3Zbs',
    appId: '1:578610636419:android:760a732ebdc03f73a35db6',
    messagingSenderId: '578610636419',
    projectId: 'direkapp-a48a8',
    storageBucket: 'direkapp-a48a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL4LSxtzJQh_S-hO0gjCRCxfcPveqPXUo',
    appId: '1:578610636419:ios:e951c442b7760619a35db6',
    messagingSenderId: '578610636419',
    projectId: 'direkapp-a48a8',
    storageBucket: 'direkapp-a48a8.appspot.com',
    iosClientId: '578610636419-ea83o56v2rjq90u1jledfj0ql1cnu7da.apps.googleusercontent.com',
    iosBundleId: 'com.example.direkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL4LSxtzJQh_S-hO0gjCRCxfcPveqPXUo',
    appId: '1:578610636419:ios:10d20a939a3b4feaa35db6',
    messagingSenderId: '578610636419',
    projectId: 'direkapp-a48a8',
    storageBucket: 'direkapp-a48a8.appspot.com',
    iosClientId: '578610636419-gp8o5qvp8ngl0o10a7up4prbqjhs87dk.apps.googleusercontent.com',
    iosBundleId: 'com.example.direkapp.RunnerTests',
  );
}
